framework:
  default_locale: fr
  translator:
#    fallbacks: ['fr']
    #        enabled: false
    default_path: '%kernel.project_dir%/translations'
    #    fallbacks:
    #      - fr
    logging: false
#        logging: false
